"""One copy of the app, on one device.

The identifier is generated by the client and survives restarts, not
reinstalls — so this table counts installations, never people and never devices.
It is not a credential either: anybody can send any uuid. What authenticates a
later call is the session token handed back, and that is a different module's
problem.
"""

import uuid
from datetime import datetime
from enum import StrEnum

from sqlalchemy import Enum, String, Uuid, func
from sqlalchemy.orm import Mapped, mapped_column

from api.core.models import Base, TimestampMixin, UTCDateTime, utcnow


class Platform(StrEnum):
    """Where the app is running. Members are lower-case because SQLAlchemy
    persists an enum by its *name*, and the wire value is the lower-case one."""

    android = "android"
    linux = "linux"
    windows = "windows"
    web = "web"


class Install(Base, TimestampMixin):
    __tablename__ = "installs"

    id: Mapped[int] = mapped_column(primary_key=True)
    # The uuid the client generated. Unique, so a second launch finds the same
    # row rather than making another.
    public_id: Mapped[uuid.UUID] = mapped_column(Uuid, unique=True, index=True)

    # A varchar with a check constraint, not a Postgres enum: adding `ios` later
    # should not need `ALTER TYPE` in a migration.
    platform: Mapped[Platform] = mapped_column(
        Enum(Platform, name="install_platform", native_enum=False, length=16)
    )
    # Who installed it — `com.android.vending` for Play, an APK host, a
    # sideload. An open string, because Android will happily report a package
    # name nobody has heard of. Null everywhere but android.
    vendor: Mapped[str | None] = mapped_column(String(128), nullable=True)
    # What it is running *now*. Overwritten on every launch, so the row answers
    # "which version is out there" rather than "which version arrived first".
    version: Mapped[str] = mapped_column(String(32))

    last_seen_at: Mapped[datetime] = mapped_column(
        UTCDateTime, default=utcnow, server_default=func.now()
    )
