"""What `POST /init` takes and what it gives back.

The field names on the way in are the client's — `id`, `ver` — because the app
was written first, and renaming them server-side would mean translating in two
places instead of none.

`AccountOut` restates a shape the accounts module also has. That duplication is
the anticorruption layer doing its job: this module never imports that one, so
if the account shape changes, the mismatch shows up here, at the seam, rather
than silently rewriting the contract the app depends on.
"""

import uuid
from datetime import datetime

from pydantic import BaseModel, Field

from api.modules.installs.models import Platform
from api.modules.installs.ports import UpdateAction, UpdateChannel
from api.modules.installs.service import Initialised


class InitIn(BaseModel):
    """What the app says about itself on start-up."""

    #: Generated by the client, kept across restarts, new after a reinstall.
    #:
    #: **Omit it** and the launch is not written down at all: no install row, no
    #: account, no session, and an answer carrying only the update plan and the
    #: feature flags. That is the "everything stays on this device" case, and it
    #: is the client's choice to make, not ours.
    id: uuid.UUID | None = None
    platform: Platform
    #: The installer package, android only — `com.android.vending` for Play.
    #: Sending it from anywhere else is refused rather than ignored.
    vendor: str | None = Field(default=None, max_length=128)
    #: `1.4.2` or `1.4.2+37`.
    ver: str = Field(min_length=1, max_length=32)


class InstallOut(BaseModel):
    id: uuid.UUID
    #: True only on the app's very first start.
    first_run: bool
    registered_at: datetime


class AccountOut(BaseModel):
    id: str
    display_name: str
    email: str | None
    #: A guest until somebody puts an email on it — see `POST /auth/claim`.
    is_guest: bool
    is_admin: bool


class SessionOut(BaseModel):
    """`token` is null when the one you sent still works — keep using it."""

    token: str | None
    expires_at: datetime


class UpdateOut(BaseModel):
    action: UpdateAction
    #: `store` sends the user to the shop that installed the app, `self` means
    #: the build fetches `url` itself, `auto` means there is nothing to do.
    channel: UpdateChannel
    current: str
    latest: str
    minimum: str
    url: str | None


class InitOut(BaseModel):
    #: All three are null for a client that sent no install id.
    install: InstallOut | None
    account: AccountOut | None
    session: SessionOut | None
    update: UpdateOut
    #: Switches this build may see. Empty until something needs one.
    features: dict[str, bool]
    #: For a device whose clock is wrong — everything with a deadline in this
    #: response is relative to this, not to the phone.
    server_time: datetime

    @classmethod
    def of(cls, result: Initialised) -> "InitOut":
        session = result.session
        return cls(
            install=(
                None
                if result.install is None
                else InstallOut(
                    id=result.install.public_id,
                    first_run=result.install.first_run,
                    registered_at=result.install.registered_at,
                )
            ),
            account=(
                None
                if session is None
                else AccountOut(
                    id=session.account.id,
                    display_name=session.account.display_name,
                    email=session.account.email,
                    is_guest=session.account.is_guest,
                    is_admin=session.account.is_admin,
                )
            ),
            session=(
                None
                if session is None
                else SessionOut(token=session.token, expires_at=session.expires_at)
            ),
            update=UpdateOut(
                action=result.update.action,
                channel=result.update.channel,
                current=result.update.current,
                latest=result.update.latest,
                minimum=result.update.minimum,
                url=result.update.url,
            ),
            features=dict(result.features),
            server_time=result.server_time,
        )
