"""one catalogue out of several

Eight tables for one idea: two sites describe the same films, and something has
to hold the answer to which of their rows are the same film.

Three unique constraints carry the whole no-duplicates guarantee, and each
refuses a different mistake — `uq_identifier` (one IMDb id, one title, forever),
`uq_source_row` (one kinostrain slug lands once, so a re-import updates rather
than doubles) and `uq_one_row_per_source` (a title holds at most one row per
source, which is what stops one bad match fusing a film with its sequel).

`title_keys` is the keypad index: one row per digit sequence that finds a title.
Its index is a plain btree because the query is a range — `code >= '489' AND
code < '48:'` — rather than a `LIKE`, which would need `text_pattern_ops` here
and get a sequential scan without it.


Revision ID: 4b363adf5cbe
Revises: 21935473c0e5
Create Date: 2026-08-23 21:24:18.458330
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4b363adf5cbe"
down_revision: str | None = "21935473c0e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "titles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("film", "serial", name="title_kind", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("original_name", sa.String(length=300), nullable=True),
        sa.Column("year_start", sa.Integer(), nullable=True),
        sa.Column("year_end", sa.Integer(), nullable=True),
        sa.Column("poster_url", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("imdb_mark", sa.Float(), nullable=True),
        sa.Column("imdb_votes", sa.Integer(), nullable=True),
        sa.Column("rank", sa.Float(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_titles_slug"), "titles", ["slug"], unique=True)
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(["title_id"], ["titles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title_id", "number", name="uq_season"),
    )
    op.create_index(op.f("ix_seasons_title_id"), "seasons", ["title_id"], unique=False)
    op.create_table(
        "title_aliases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("folded", sa.String(length=200), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["title_id"], ["titles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title_id", "folded", "year", name="uq_alias"),
    )
    op.create_index("ix_alias_lookup", "title_aliases", ["folded", "year"], unique=False)
    op.create_index(op.f("ix_title_aliases_title_id"), "title_aliases", ["title_id"], unique=False)
    op.create_table(
        "title_identifiers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("imdb", "ashdi", name="identifier_kind", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=120), nullable=False),
        sa.ForeignKeyConstraint(["title_id"], ["titles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "value", name="uq_identifier"),
    )
    op.create_index(
        op.f("ix_title_identifiers_title_id"), "title_identifiers", ["title_id"], unique=False
    )
    op.create_table(
        "title_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["title_id"], ["titles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title_id", "code", name="uq_title_key"),
    )
    op.create_index("ix_title_key_code", "title_keys", ["code"], unique=False)
    op.create_index(op.f("ix_title_keys_title_id"), "title_keys", ["title_id"], unique=False)
    op.create_table(
        "title_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("kinostrain", "kinoukr", name="title_source", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=200), nullable=False),
        sa.Column("external_url", sa.String(length=500), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("evidence", sa.String(length=64), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["title_id"], ["titles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_source_row"),
        sa.UniqueConstraint("title_id", "source", name="uq_one_row_per_source"),
    )
    op.create_index(op.f("ix_title_sources_title_id"), "title_sources", ["title_id"], unique=False)
    op.create_table(
        "episodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("season_id", "number", name="uq_episode"),
    )
    op.create_index(op.f("ix_episodes_season_id"), "episodes", ["season_id"], unique=False)
    op.create_table(
        "streams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=True),
        sa.Column(
            "host",
            sa.Enum(
                "ashdi", "tortuga", "vsembed", name="stream_host", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column(
            "offered_by",
            sa.Enum("kinostrain", "kinoukr", name="stream_source", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["episode_id"], ["episodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["title_id"], ["titles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title_id", "host", "external_id", name="uq_stream"),
    )
    op.create_index("ix_stream_external", "streams", ["host", "external_id"], unique=False)
    op.create_index(op.f("ix_streams_episode_id"), "streams", ["episode_id"], unique=False)
    op.create_index(op.f("ix_streams_title_id"), "streams", ["title_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_streams_title_id"), table_name="streams")
    op.drop_index(op.f("ix_streams_episode_id"), table_name="streams")
    op.drop_index("ix_stream_external", table_name="streams")
    op.drop_table("streams")
    op.drop_index(op.f("ix_episodes_season_id"), table_name="episodes")
    op.drop_table("episodes")
    op.drop_index(op.f("ix_title_sources_title_id"), table_name="title_sources")
    op.drop_table("title_sources")
    op.drop_index(op.f("ix_title_keys_title_id"), table_name="title_keys")
    op.drop_index("ix_title_key_code", table_name="title_keys")
    op.drop_table("title_keys")
    op.drop_index(op.f("ix_title_identifiers_title_id"), table_name="title_identifiers")
    op.drop_table("title_identifiers")
    op.drop_index(op.f("ix_title_aliases_title_id"), table_name="title_aliases")
    op.drop_index("ix_alias_lookup", table_name="title_aliases")
    op.drop_table("title_aliases")
    op.drop_index(op.f("ix_seasons_title_id"), table_name="seasons")
    op.drop_table("seasons")
    op.drop_index(op.f("ix_titles_slug"), table_name="titles")
    op.drop_table("titles")
    # ### end Alembic commands ###
